### ISSUE TITLE
Telemere: improved OpenTelemetry interop

### ISSUE THREAD

**Issue by ptaoussanis** [taoensso/roadmap#16]
**Task**: Look for opportunities to improve [Telemere](https://www.taoensso.com/telemere)'s OpenTelemetry support - incl. first-class conveyance of Telemere's trace info, etc.

**Motivation**: Telemere already supports basic interop with OpenTelemetry via its [OpenTelemetry logging handler](https://cljdoc.org/d/com.taoensso/telemere/1.0.0-beta10/api/taoensso.telemere.open-telemetry#handler:open-telemetry-logger), but there's probably further opportunities to convey more information (notably Telemere spans) to OpenTelemetry in a way that better allows it to digest this info.

Pointers to relevant docs, etc. would be helpful if you have them!

**Comment by robert-stuttaford** [comment]
Watching Telemere with keen interest :-D We use Timbre for logging today, and have big plans to make use of Honeycomb  in our next arc of observability work (we use https://github.com/steffan-westcott/clj-otel for our experiments at the moment). 

Telemere looks like it would fit very neatly into our plans!

**Comment by duzunov** [comment]
I would be very happy to test OTel support in Telemere

**Comment by mikechiama** [comment]
Really interested to see where the otel thread is leading! Following

**Comment by ptaoussanis** [comment]
Hey folks! I'll be ready soon for some (very) early testers / feedback on Telemere's OpenTelemetry integration.

For anyone interested - please ping me by email (peter@taoensso.com) or [Clojurians Slack DM](https://clojurians.slack.com/team/UASETR481) and I'll send instructions on how you can help.

Thanks! 🙏

**Comment by ptaoussanis** [comment]
Hi folks! 👋 I've just pushed [Telemere v1 beta 18](https://github.com/taoensso/telemere/releases/tag/v1.0.0-beta18) to Clojars.

This includes the first experimental support for automatically emitting **correlated logs and tracing data** to OpenTelemetry.

See [here](https://github.com/taoensso/telemere/wiki/3-Config#opentelemetry) for info on getting started. There's no special usage instructions - in principle you should just be able to use the regular Telemere API as always, and your signals will just be auto-converted in an appropriate way.

I'm not a big user of OpenTelemetry myself, so will definitely **need help with testing and feedback** from folks interested in this feature! 🙏 The kinds of feedback I'm looking for include:

- **Usage reports** (is everything working correctly, is it intuitive, etc.?)
- Feedback on **output** (how are the attribute names, coercions, etc.?)
- Any **limitations** (anything you want to do but can't?)
- Any other thoughts or suggestions! Now's the perfect time to get changes in, before Telemere itself is marked as stable.

The best places to leave feedback:

- The [#telemere slack channel](https://www.taoensso.com/telemere/slack)
- The [Telemere GitHub](https://www.taoensso.com/telemere) (feel free to open an issue)

Thanks! Cheers :-)

**Comment by ptaoussanis** [comment]
Update: [v1 beta 21](https://github.com/taoensso/telemere/releases/tag/v1.0.0-beta21) is now on Clojars and includes improved integration with OpenTelemetry tracing.

Telemere's tracing forms now emit code that interops directly with the OpenTelemetry tracing API when it’s present. This means that Telemere spans will show as expected within spans created by other (auto/manual) OpenTelemetry tools, and vice versa.

Barring any unexpected issues or suggested changes, this feature should now basically be complete.

**Comment by ptaoussanis** [comment]
Closing for now, but please feel free to ping if anyone runs into issues!
